//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 04:25:26 PM SAST 
//


package com.payjar.web.controller.api.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import https.www_payu_co_za.payumaploader.PayUMapLoader;


/**
 * <p>Java class for iPaymentMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iPaymentMethod">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.payu.co.za/PayUMapLoader}PayUMapLoader">
 *       &lt;sequence>
 *         &lt;element name="defaultPM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pmId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iPaymentMethod", propOrder = {
    "defaultPM",
    "pmId"
})
@XmlSeeAlso({
    AutoPay.class,
    Soulstace.class,
    Sbux.class,
    ThirdParty.class,
    BankDepositDetails.class,
    BankAccount.class,
    LoyaltyCard.class,
    Fraud.class,
    Globalpay.class,
    BankTransfer.class,
    EftBankTransfer.class,
    EWalletPagaTech.class,
    Mobicred.class,
    EWalletMPesa.class,
    Sva.class,
    Rcs.class,
    Ebucks.class,
    DiscoveryMiles.class,
    EWallet.class,
    Eft.class,
    DebitCard.class,
    CreditCard.class,
    PayPal.class
})
public abstract class IPaymentMethod
    extends PayUMapLoader
{

    protected String defaultPM;
    protected String pmId;

    /**
     * Gets the value of the defaultPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultPM() {
        return defaultPM;
    }

    /**
     * Sets the value of the defaultPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultPM(String value) {
        this.defaultPM = value;
    }

    /**
     * Gets the value of the pmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmId() {
        return pmId;
    }

    /**
     * Sets the value of the pmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmId(String value) {
        this.pmId = value;
    }

}
