//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 04:25:26 PM SAST 
//


package https.www_payu_co_za.lookuptransactionresponsemessage;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_payu_co_za.lookuptransactionresponsemessage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_payu_co_za.lookuptransactionresponsemessage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LookupTransactionResponseMessage }
     * 
     */
    public LookupTransactionResponseMessage createLookupTransactionResponseMessage() {
        return new LookupTransactionResponseMessage();
    }

    /**
     * Create an instance of {@link LookupTransactionResponseMessage.LookupData }
     * 
     */
    public LookupTransactionResponseMessage.LookupData createLookupTransactionResponseMessageLookupData() {
        return new LookupTransactionResponseMessage.LookupData();
    }

    /**
     * Create an instance of {@link LookupTransactionResponseMessage.LookupData.Entry }
     * 
     */
    public LookupTransactionResponseMessage.LookupData.Entry createLookupTransactionResponseMessageLookupDataEntry() {
        return new LookupTransactionResponseMessage.LookupData.Entry();
    }

}
