//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 04:25:26 PM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.payu.co.za/LookupTransactionResponseMessage")
package https.www_payu_co_za.lookuptransactionresponsemessage;
