//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 04:25:26 PM SAST 
//


package https.www_payu_co_za.payumaploader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.payjar.web.controller.api.soap.AdditionalInfo;
import com.payjar.web.controller.api.soap.Balance;
import com.payjar.web.controller.api.soap.Basket;
import com.payjar.web.controller.api.soap.Credit;
import com.payjar.web.controller.api.soap.CustomField;
import com.payjar.web.controller.api.soap.Customer;
import com.payjar.web.controller.api.soap.IPaymentMethod;
import com.payjar.web.controller.api.soap.RecurringDetails;
import com.payjar.web.controller.api.soap.Redirect;
import com.payjar.web.controller.api.soap.TransactionRecord;
import com.payjar.web.controller.api.soap.WalletBalance;
import https.www_payu_co_za.deletetransactionresponsemessage.DeleteTransactionResponseMessage;
import https.www_payu_co_za.deletetransactionresponsemessage.ManagePaymentMethodResponseMessage;
import https.www_payu_co_za.dotransactionresponsemessage.DoTransactionResponseMessage;
import https.www_payu_co_za.gettransactionresponsemessage.GetTransactionResponseMessage;
import https.www_payu_co_za.lookuptransactionresponsemessage.LookupTransactionResponseMessage;
import https.www_payu_co_za.settransactionresponsemessage.SetTransactionResponseMessage;


/**
 * <p>Java class for PayUMapLoader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayUMapLoader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayUMapLoader")
@XmlSeeAlso({
    Basket.class,
    WalletBalance.class,
    Balance.class,
    AdditionalInfo.class,
    Credit.class,
    CustomField.class,
    TransactionRecord.class,
    Redirect.class,
    RecurringDetails.class,
    IPaymentMethod.class,
    Customer.class,
    ManagePaymentMethodResponseMessage.class,
    DeleteTransactionResponseMessage.class,
    GetTransactionResponseMessage.class,
    DoTransactionResponseMessage.class,
    SetTransactionResponseMessage.class,
    LookupTransactionResponseMessage.class
})
public abstract class PayUMapLoader {


}
